# Stage 1: Build stage
FROM python:3.11-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the requirements file into the image
COPY requirements.txt .

# Install build dependencies
RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY ./.env notetaker_agent.py ./

# Stage 3: Production stage
FROM python:3.11-alpine AS prod

# Set the working directory
WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /app .

# Expose the necessary port for production
EXPOSE 8000

# Create a non-root user to run the application
RUN adduser -D appuser

# Change ownership of the application folder
RUN chown -R appuser /app

# Switch to the non-root user
USER appuser

# Command to run the application in production mode
CMD ["python", "notetaker_agent.py"]